config/routes.rb
Rails.application.routes.draw do
  root 'messages#index'
  devise_for :users
  resources :messages, only: [:index, :create]

  mount ActionCable.server, at: '/cable'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
  validates :user_id, presence: true
  validates :content, presence: true

  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable

  validates :name, presence: true

  has_many :messages,
           dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def index
    @messages = Message.all
  end
  
  def create
    @message = current_user.messages.new(message_params)
    if @message.save
      ActionCable.server.broadcast("chatbox_channel", { rendered_msg: render_message(@message) })
    end
  end

  private
    def message_params
      params.require(:message).permit(:content)
    end

    def render_message(message)
      render(partial:'message', locals: { message: message})
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_alerts.html.haml
%p.notice= notice
%p.alert= alert

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Chatbox
    %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}/
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render 'layouts/alerts'
    .container
      = yield

app/views/messages/_message.html.haml
%p.mb-1 #{message.user.name}: #{message.content}

app/views/messages/_message_form.html.haml
= form_with url: messages_url, method: :post,local: false, id: 'message_content', class: 'd-flex' do |form|
  = form.text_area 'message[content]', id: 'message-content', class: 'post-input-field m-0 flex-grow-1'
  = form.submit 'Send', id: 'send', class: 'btn btn-primary btn-sm'

app/views/messages/index.html.haml
.container
  .text-center.mb-5
    %h1 Let's talk
  .row.h-100
    .col-sm-9
      .card.h-100
        .card-body
          #message-box.card-text.half-height
            = render @messages
        .card-footer.bg-white
          = render 'message_form'
    .col-sm-3
      .card.h-100
        .card-body
          .card-text 
            %h5 Users online
    

  = link_to 'Log out', destroy_user_session_url, method: :delete, class: 'btn btn-primary mt-4'

app/views/pages/home.html.haml
.container
  .text-center.mb-5
    %h1 Let's talk
  .half-height
    .row.h-100
      .col-sm-9
        .card.h-100
          .card-body
            .card-text
              %h5 Messages
      .col-sm-3
        .card.h-100
          .card-body
            .card-text 
              %h5 Users online
  

  = link_to 'Log out', destroy_user_session_url, method: :delete, class: 'btn btn-primary mt-4'